### PR TITLE
Make gunicorn app removable

### PR DESCRIPTION
**Pull request by jcbashdown**
I think this should all work apart from logrotate file here:

https://github.com/alphagov/pp-puppet/blob/29f2b87f18527b60065109be4a5c6893a104afbb/modules/performanceplatform/manifests/python_app.pp#L64

Not quite sure what this does so I don't know if it needs removing explicitly. Seems to fill out a template?

### CODE REVIEW

**Comment by tombooth** [comment]
The logstashforwarder::file sets up the pushing of logs over to lumberjack. The resource comes from an elasticsearch maintained module that can be found here:

https://github.com/elasticsearch/puppet-logstashforwarder

The file resource doesn't support ensure, so we should purge the configdir on each run:

https://github.com/elasticsearch/puppet-logstashforwarder/blob/master/manifests/init.pp#L128

**Comment by tombooth** [comment]
@jcbashdown just a ping about the comment, would love to merge.

**Comment by jcbashdown** [comment]
Hey, sorry @tombooth. Did see it but I still wasn't immediately sure what to do. I could probably figure it out with a small amount of looking at those links but then I got caught up with this disk space thing on the backup boxes. Will try and look into it soon!

**Comment by tombooth** [comment]
Whoops

**Comment by jcbashdown** [comment]
@tombooth Is this what you had in mind? Sorry, took me ages to get the time to actually look at those links.

**Pull request merged**
